require "rake/clean"
DIR = Time.now().to_i.to_s

CLOBBER << "graph.pdf"
CLOBBER << "changes.pdf"
CLEAN << "clusters.csv"
CLEAN << "input_for_clustering.csv"

task default: ["graph.pdf", "changes.pdf"]

task "show" => DIR do
  spawn "evince", File.join(DIR, "graph.pdf")
  spawn "evince", File.join(DIR, "changes.pdf")
end

file DIR => ["graph.pdf", "changes.pdf"] do
  mkdir DIR
  cp "changes.pdf", File.join(DIR, "changes.pdf")
  cp "graph.pdf", File.join(DIR, "graph.pdf")  
end

file "graph.pdf" => ["clusters.csv", "graph.R", "read-dataset.R"] do
  sh "R -f graph.R"
  mv "Rplots.pdf", "graph.pdf"
end

file "changes.pdf" => ["clusters.csv", "graph-cluster-variables.R", "read-dataset.R"] do
  sh "R -f graph-cluster-variables.R"
  mv "Rplots.pdf", "changes.pdf"
end

  sh "cluster input_for_clustering.csv 1"
file "clusters.csv" => ["input_for_clustering.csv", "Rakefile"] do
end

file "input_for_clustering.csv" => ["prepare-data.R", "read-dataset.R"] do
  sh "R -f prepare-data.R"
end
